"""Generate custom_components/good_days/haftarah_data.py from Hebcal's leyning data.

Source: https://github.com/hebcal/hebcal-leyning (src/aliyot.json, src/holiday-readings.json),
BSD-2-Clause, Copyright (c) 2020 hebcal; license text in scripts/data/HEBCAL-LICENSE.txt.

Run from the repo root: python scripts/gen_haftarah.py
"""
from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "scripts" / "data"
OUT = ROOT / "custom_components" / "good_days" / "haftarah_data.py"

# hdate Parasha keys (lower case) for Hebcal's combined parashiyot.
COMBINED = {
    (22, 23): "vayakhel_pekudei",
    (27, 28): "tazria_metzora",
    (29, 30): "achrei_mot_kedoshim",
    (32, 33): "behar_bechukotai",
    (39, 40): "chukat_balak",
    (42, 43): "matot_masei",
    (51, 52): "nitzavim_vayeilech",
}

# The Hebcal special readings this integration uses (plain Shabbat only).
SPECIALS = [
    "Shabbat Shekalim",
    "Shabbat Zachor",
    "Shabbat Parah",
    "Shabbat HaChodesh",
    "Shabbat HaGadol",
    "Shabbat Shuva (with Vayeilech)",
    "Shabbat Shuva (with Ha'azinu)",
    "Shabbat Rosh Chodesh",
    "Shabbat Machar Chodesh",
    "Shabbat Rosh Chodesh Chanukah",
    "Chanukah Day 1 (on Shabbat)",
    "Chanukah Day 8 (on Shabbat)",
    "Pinchas occurring after 17 Tammuz",
    "Ki Teitzei with 3rd Haftarah of Consolation",
    "Kedoshim following Special Shabbat",
    "Masei on Shabbat Rosh Chodesh",
]


def parts(value) -> tuple:
    if not value:
        return ()
    items = value if isinstance(value, list) else [value]
    return tuple((p["k"], p["b"], p["e"]) for p in items)


def main() -> None:
    aliyot = json.loads((DATA / "hebcal-aliyot.json").read_text(encoding="utf-8"))
    holiday = json.loads((DATA / "hebcal-holiday-readings.json").read_text(encoding="utf-8"))
    from hdate.parasha import Parasha  # noqa: PLC0415  (dev-time only)

    by_num = {p.value: p.name.lower() for p in Parasha if 1 <= p.value <= 54}
    parasha: dict[str, tuple] = {}
    for raw in aliyot.values():
        num = raw["num"]
        key = COMBINED[tuple(num)] if isinstance(num, list) else by_num[num]
        haft = parts(raw.get("haft"))
        parasha[key] = (haft, parts(raw.get("seph")) or haft) if haft else ((), ())

    special: dict[str, tuple] = {}
    for name in SPECIALS:
        raw = holiday[name]
        haft = parts(raw["haft"])
        special[name] = (haft, parts(raw.get("seph")) or haft)

    books = sorted({p[0] for h, s in [*parasha.values(), *special.values()] for p in (*h, *s)})
    lines = [
        '"""Haftarah references. GENERATED by scripts/gen_haftarah.py; do not edit.',
        "",
        "Data from Hebcal leyning (https://github.com/hebcal/hebcal-leyning), BSD-2-Clause,",
        "Copyright (c) 2020 hebcal. Each value: (ashkenazi, sephardi), each a tuple of",
        "(book, first chapter:verse, last chapter:verse) parts.",
        '"""',
        "",
        f"BOOKS = {books!r}",
        "",
        "PARASHA = {",
        *(f"    {k!r}: {v!r}," for k, v in sorted(parasha.items())),
        "}",
        "",
        "SPECIAL = {",
        *(f"    {k!r}: {v!r}," for k, v in special.items()),
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.name}: {len(parasha)} parashiyot, {len(special)} specials, {len(books)} books")


if __name__ == "__main__":
    main()
